added modals
mymymyr/react-burger pull request #2
Opened 2022-11-11 20:55 UTC by mymymyr

2022-11-12 07:57 UTC, randomroot requested changes
**Добрый день!**

Вы **успешно** добавили модальные окна и запрос на сервер за ингредиентами в ваш проект, **отлично** описываете PropTypes, код **хорошо** отформатирован и не содержит лишнего, дизайн **соответствует** заданию, **прекрасная** работа! 👍 

Тем не менее, для успешного завершения спринта вам необходимо ознакомиться с комментариями, указанными в рамках ревью, и провести **исправления**, обратив особое внимание на следующие моменты:

- У `ModalOverlay` не должно быть children, это просто компонент **подложки**, а не контейнер;
- Модальное окно является **универсальным** решением для показа набора элементов во всплывающем окне. В нём не должно быть привязки/пропсов к той или иной функциональности проекта. поэтому хардкод типов внутри него - не совсем удачная практика, которую будет **сложно поддерживать**;
- Не следует использовать **пустой объект** `{}` для обозначения отсутствующего значения в стейтах, вместо это применяйте `null`;
- Если данные идут как единый объект, то **не следует разбивать его** на части, передавая во множестве пропсов, используйте его полностью и одним пропсов (см. ingredient-details.jsx)

Также, в рамках работы были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**.

---

**Хорошего вам настроения и отличных выходных!** 🐈

2022-11-12 07:57 UTC, randomroot commented on src/components/modal/modal.jsx
> +    const modalRoot = document.getElementById("react-modals");
🟡 **Можно улучшить:**

Данную константу имеет вынести за пределы компонента, чтобы не пересоздавать её на каждом рендере

2022-11-12 07:57 UTC, randomroot commented on src/components/modal/modal.jsx
> +                        props.type === 'ingredient' ? (
🔴 **Нужно исправить:**

Модальное окно - это **универсальное** решение для показа набора элементов во всплывающем окне. В нём **не должно** быть привязки/пропсов к той или иной функциональности проекта, а каждой его экземпляр - отвечает за вывод одного, связанного по смыслу, набора контента. Типов может становится всё больше и такой компонент станет сложно поддерживать в текущем виде. 

Следует убрать данный пропс и передавать содержимое напрямую:
В качестве пропсов следует указать минимальный набор: `title` - заголовок окна, `onClose` - функция его закрытия, `children` - вложенные элементы (специально указывать не нужно, достаточно вложить компоненты).

2022-11-12 07:57 UTC, randomroot commented on src/components/modal-overlay/modal-overlay.jsx
> +        <div className={ModalOverlayStyles.overlay} onClick={props.onCloseModal} ref={props.modalOverlayRef}>
🔴 **Нужно исправить:**

У `ModalOverlay` не должно быть children, это просто компонент подложки, а не контейнер

2022-11-12 07:57 UTC, randomroot commented on src/components/ingredient-details/ingredient-details.jsx
> +    ...dataItemPropTypes
🔴 **Нужно исправить:**

 Ингредиент следует передавать в одном пропсе, не следует разделять объект на множество пропсов

```js
IngredientDetails.propTypes = {
   onCloseModal: PropTypes.func.isRequired,
   ingredient: PropTypes.shape(dataItemPropTypes).isRequired
}
```

2022-11-12 07:57 UTC, randomroot commented on src/components/app/app.jsx
> +          <div style={{ overflow: 'hidden' }}>
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2022-11-12 07:57 UTC, randomroot commented on src/components/app/app.jsx
> +              <Modal onCloseModal={handleCloseModal} item={item} type={modalType}></Modal>
🟡 **Можно улучшить:**

Модальные окна не относятся ко всему приложению в целом, а конкретно к его отдельным компонентам, с которыми они связаны информацией, поэтому следует перенести их именно туда.
Это поможет упростить читабельность вашего кода (получится быстрее найти нужный код и уменьшит размер App.jsx, который лучше поддерживать в простом состоянии, как одну из точек входа) и уменьшит кол-во пропсов передаваемых в компоненты списка ингредиентов и конструктора.

2022-11-12 07:57 UTC, randomroot commented on src/components/app/app.jsx
> +  const [item, setItem] = useState({});
🔴 **Нужно исправить:**

**Здесь и далее по коду** не следует использовать пустой объект для отсутствующего значения, вместо это применяйте `null` - так вы избежите возможных проблем в будущем, связанных с возможным обращением по несуществующим ключам, особенно, когда есть вложенность.

2022-11-12 07:57 UTC, randomroot commented on src/components/app/app.jsx
> +        const res = await fetch(url);
🟡 **Можно улучшить:**

В дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции:

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-11-12 07:57 UTC, randomroot commented on src/components/app/app.jsx
> +  const url = 'https://norma.nomoreparties.space/api/ingredients';
🟡 **Можно улучшить:**

Вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`. Так вы сможете переиспользовать базовый адрес в нескольких функциях в будущем

2022-11-12 07:57 UTC, randomroot commented on src/components/app/app.jsx
> +  const [modalVisible, setModalVisible] = useState(false);
🟡 **Можно улучшить:**

Обратите внимание, что если вынести модальные окна по разным файла, то критерием его открытия будет служить наличие в переменных ингредиента/заказа данных и отдельная переменная `visible` не будет более нужна

2022-11-12 07:57 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
>  function BurgerIngredients(props) {
🟡 **Можно улучшить:**

**Здесь и далее по коду** рекомендуется применять декомпозицию пропсов, чтобы исключить дублирование обращения к переменной пропс и улучшить визуально код (быстрее распознается, какие пропсы есть у компонента):

```js
function BurgerIngredients({ data, openModal }) {
...
}
```

2022-11-12 09:37 UTC, mymymyr commented on src/components/app/app.jsx
> +        const res = await fetch(url);
fix

2022-11-12 09:37 UTC, mymymyr commented on src/components/app/app.jsx
> +  const url = 'https://norma.nomoreparties.space/api/ingredients';
fix

2022-11-12 10:02 UTC, mymymyr commented on src/components/modal-overlay/modal-overlay.jsx
> +        <div className={ModalOverlayStyles.overlay} onClick={props.onCloseModal} ref={props.modalOverlayRef}>
fix

2022-11-12 10:52 UTC, mymymyr commented on src/components/modal/modal.jsx
> +    const modalRoot = document.getElementById("react-modals");
fix

2022-11-12 10:52 UTC, mymymyr commented on src/components/modal/modal.jsx
> +                        props.type === 'ingredient' ? (
fix

2022-11-12 10:53 UTC, mymymyr commented on src/components/ingredient-details/ingredient-details.jsx
> +    ...dataItemPropTypes
fix

2022-11-12 11:00 UTC, mymymyr commented on src/components/app/app.jsx
> +          <div style={{ overflow: 'hidden' }}>
fix

2022-11-12 11:01 UTC, mymymyr commented on src/components/app/app.jsx
> +  const [item, setItem] = useState({});
fix

2022-11-12 11:04 UTC, mymymyr commented on src/components/burger-ingredients/burger-ingredients.jsx
>  function BurgerIngredients(props) {
fix

2022-11-12 17:18 UTC, randomroot requested changes
**Здравствуйте!**

Вы внесли немало правок для исправления выявленных в работе неточностей, а также улучшили качество своего кода, однако для окончательного завершения работы над спринтом вам следует провести еще один ряд корректировок, связанных со следующими моментами:

- В конструкторе ингредиентов в начинку попали булки, следует предварительно отфильтровать значения по типу `.type !== 'bun'` (https://disk.yandex.ru/i/-2nT_BY1J4HLnA);
- Названия переменных внутри компонентов не следует начинать с большой буквы, такой подход только для названий React компонентов, необходимо применять `camelCase` или `UPPER_CASE` для констант, которые выносятся за их пределы.

**Желаю вам отличных выходных!** 🐈

2022-11-12 17:18 UTC, randomroot commented on src/components/app/app.jsx
> +  const Modals = { Ingredient: 'ingredient', Order: 'order' };
🔴 **Нужно исправить:**

Названия переменных не следует начинать с большой буквы, такой подход только для React компонентов, поэтому её следует переименовать в `camelCase` или вынести выше за пределы `App` и задать `UPPER_CASE` стиль:

```jsx
const MODALS =  { Ingredient: 'ingredient', Order: 'order' };

function App() {
...
```

2022-11-12 17:18 UTC, randomroot commented on src/components/app/app.jsx
> +              <Modal onCloseModal={handleCloseModal} title='Детали ингредиента'>
🟡 **Можно улучшить:**

JSX элементы рекомендуется оборачивать в круглые скобки в рамках таких выражений, чтобы избегать возможных проблем с автоформатированием кода (см. https://medium.com/as-a-coder/why-you-should-wrap-your-jsx-with-parentheses-d7670293e45)

2022-11-12 17:18 UTC, randomroot commented on src/components/modal/modal.jsx
> +    title: PropTypes.string.isRequired
🟡 **Можно улучшить:**

Значение пропса `title` можно сделать необязательным, чтобы не передавать пустую строку при необходимости скрыть заголовок и задать ему значение по-умолчанию в декомпозиции:

```js
function Modal({ title = '', onCloseModal, children }) {
```

2022-11-12 17:18 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                    {data.map((item, index) => (
🔴 **Нужно исправить:**

В конструкторе ингредиентов в начинку попали булки, следует предварительно отфильтровать значения по типу `.type !== 'bun'` (https://disk.yandex.ru/i/-2nT_BY1J4HLnA);

2022-11-13 04:03 UTC, mymymyr commented on src/components/app/app.jsx
> +  const Modals = { Ingredient: 'ingredient', Order: 'order' };
fix

2022-11-13 04:03 UTC, mymymyr commented on src/components/app/app.jsx
> +              <Modal onCloseModal={handleCloseModal} title='Детали ингредиента'>
fix

2022-11-13 04:03 UTC, mymymyr commented on src/components/modal/modal.jsx
> +    title: PropTypes.string.isRequired
fix

2022-11-13 04:03 UTC, mymymyr commented on src/components/burger-constructor/burger-constructor.jsx
> +                    {data.map((item, index) => (
fix

2022-11-13 06:47 UTC, randomroot approved these changes
🟢 **Работа принята:**

Необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Перед тем, как слить ваш PR, обратите внимание на комментарий относительно наименований переменных где описываются `PropTypes`.

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-11-13 06:47 UTC, randomroot commented on src/components/utils/dataPropTypes.js
> +const BURGER_PROP_TYPES = PropTypes.shape({
🟡 **Можно улучшить:**

`PropTypes` не являются обычными константами в своём понимании, поэтому на них не распространяется правило `UPPER_CASE`, имеет смысл вернуть предыдущий вид

2022-11-22 14:39 UTC, merged