create order feed, order profile, use WebSocket
mymymyr/react-burger pull request #6
Opened 2023-02-03 20:04 UTC by mymymyr

2023-02-03 20:58 UTC, andryxxa93 requested changes
Отличная работа!
Что понравилось:
- На каждый обработчик WS-соединения создан экшен. 
- Правильное использование `useMemo`
- Хороший `codestyle`

Есть только одно небольшое замечание -
Сокет соединение должно открываться когда юзер переходит на "Историю заказов" или "Ленту заказов" и сразу же закрываться когда он их покидает. Сейчас судя по экшенам соединение остается открытым.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачи!

2023-02-03 20:58 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  const { wsConnected, wsConnectedWithToken, startHeartbeat, startHeartbeatWithToken } = useSelector(
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-02-03 20:58 UTC, andryxxa93 commented on src/components/order/order.jsx
> +    const sum = (bun ? bun.price * 2 : 0) +
**Можно лучше**
Инициализацию `sum` так же лучше поместить в `useMemo`

2023-02-03 20:58 UTC, andryxxa93 commented on src/components/order/order.jsx
> +    bun ? ingredients = [bun, ...internalIngredients] : ingredients = [...internalIngredients];
**Можно лучше**
`ingredients` лучше поместить в `useState` а вот эту строчку в `useEffect` иначе сейчас данная операция будет происходить каждый рендер

2023-02-03 20:58 UTC, andryxxa93 commented on src/pages/feed.jsx
> +                                useMemo(() => orders.map((order) =>
**Можно лучше**
Желательно разделять логику и представление. Когда они смешаны это затрудняет чтение и дебажинг кода.

2023-02-04 13:39 UTC, mymymyr commented on src/components/order/order.jsx
> +    const sum = (bun ? bun.price * 2 : 0) +
done

2023-02-04 15:06 UTC, mymymyr commented on src/components/order/order.jsx
> +    bun ? ingredients = [bun, ...internalIngredients] : ingredients = [...internalIngredients];
done

2023-02-04 18:23 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-02-04 18:53 UTC, merged